version: '2'
services:

  cassandra:
    image: cassandra:latest
    container_name: "cassandra"
    volumes:
      - "./data:/var/lib/cassandra"
    ports:
      - "7000:7000"
      - "9042:9042"
   
networks:
  default:
    external:
      name: "analytics"
