version: '2'
services:

  mysql:
    image: library/mysql:8
    container_name: mysql
    command: "mysqld \
              --character-set-server=utf8 \
              --collation-server=utf8_general_ci \
              --max_allowed_packet=1G \
              --default-authentication-plugin=mysql_native_password \
              --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    volumes:
      - "/home/mseaton/environments/humci/mysqldata:/var/lib/mysql"
    ports:
      - "3308:3306"

networks:
  default:
    external:
      name: "analytics-incubator-network"