version: '2'
services:

  mysql:
    image: library/mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: "mysqld \
              --character-set-server=utf8 \
              --collation-server=utf8_general_ci \
              --max_allowed_packet=1G \
              --innodb-buffer-pool-size=2G \
              --user=mysql \
              --server-id=100002 \
              --log-bin=mysql-bin \
              --binlog_format=ROW \
              --max_binlog_size=100M \
              --default-authentication-plugin=mysql_native_password \
              --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - "3308:3306"

networks:
  default:
    external:
      name: "analytics"